name: Build Whisper! App

# Run build on all branches and tags
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: build the application
    steps: 
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: install dependencies
        run: bun install
      - name: build code
        run: bun build src/* --outdir dist --minify
      - name: build incons
        run: bun run ./build/build-iconify.ts
      - name: bundle
        run: |
          mkdir bundle/
          cp -R dist bundle/
          cp -R img bundle/
          cp -R css bundle/
          cp index.html bundle/